SESSION_SECRET = ENV['SECRET_KEY'] || 'aaaaa'

MONGOLAB_URI = ENV['MONGOLAB_URI']

ANN_TYPE = 'com.floatboth.appvertise.ad'
ADN_ID = ENV['ADN_ID']
ADN_SECRET = ENV['ADN_SECRET']
ADN_TOKEN = ENV['ADN_TOKEN']

PERCENT_CUT = 30
BTC_PER_HOUR = ENV['BTC_PER_HOUR'].to_f
BTC_ADR = ENV['BTC_ADR']
BTC_GUID = ENV['BTC_GUID']
BTC_PASSWORD = ENV['BTC_PASSWORD']
BTC_PASSWORD2 = ENV['BTC_PASSWORD2']

AWS_KEY = ENV['AWS_KEY']
AWS_SECRET = ENV['AWS_SECRET']
AWS_BUCKET = ENV['AWS_BUCKET']
